// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: '/minigames/minigame_selection',
    uri: Uri.parse('/minigames/minigame_selection'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(
    key: '/minigames/snake/snake_game',
    uri: Uri.parse('/minigames/snake/snake_game'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(key: '/login', uri: Uri.parse('/login'), routeBuilder: b2Builder),
  RouteEntity(
    key: '/splash',
    uri: Uri.parse('/splash'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(key: '/home', uri: Uri.parse('/home'), routeBuilder: b4Builder),
  RouteEntity(
    key: '/quiz/[id]/quiz',
    uri: Uri.parse('/quiz/[id]/quiz'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(
    key: '/module/[id]/show',
    uri: Uri.parse('/module/[id]/show'),
    routeBuilder: b6Builder,
  ),
  RouteEntity(
    key: '/module/create/create_module',
    uri: Uri.parse('/module/create/create_module'),
    routeBuilder: b7Builder,
  ),
  RouteEntity(
    key: '/module/create_questions/[moduleId]/form_questions',
    uri: Uri.parse('/module/create_questions/[moduleId]/form_questions'),
    routeBuilder: b8Builder,
  ),
  RouteEntity(
    key: '/settings',
    uri: Uri.parse('/settings'),
    routeBuilder: b9Builder,
  ),
];

const routePaths = (
  path: '/',
  minigames: (
    path: '/minigames',
    minigameSelection: '/minigames/minigame_selection',
    snake: (path: '/minigames/snake', snakeGame: '/minigames/snake/snake_game'),
  ),
  login: '/login',
  splash: '/splash',
  home: '/home',
  quiz: (path: '/quiz', $id: (path: '/quiz/[id]', quiz: '/quiz/[id]/quiz')),
  module: (
    path: '/module',
    $id: (path: '/module/[id]', show: '/module/[id]/show'),
    create: (
      path: '/module/create',
      createModule: '/module/create/create_module',
    ),
    createQuestions: (
      path: '/module/create_questions',
      $moduleId: (
        path: '/module/create_questions/[moduleId]',
        formQuestions: '/module/create_questions/[moduleId]/form_questions',
      ),
    ),
  ),
  settings: '/settings',
);
