// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: '/login', uri: Uri.parse('/login'), routeBuilder: b0Builder),
  RouteEntity(
    key: '/splash',
    uri: Uri.parse('/splash'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(key: '/home', uri: Uri.parse('/home'), routeBuilder: b2Builder),
  RouteEntity(
    key: '/quiz/[id]/quiz',
    uri: Uri.parse('/quiz/[id]/quiz'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: '/module/[id]/show',
    uri: Uri.parse('/module/[id]/show'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: '/settings',
    uri: Uri.parse('/settings'),
    routeBuilder: b5Builder,
  ),
];

const routePaths = (
  path: '/',
  login: '/login',
  splash: '/splash',
  home: '/home',
  quiz: (path: '/quiz', $id: (path: '/quiz/[id]', quiz: '/quiz/[id]/quiz')),
  module: (
    path: '/module',
    $id: (path: '/module/[id]', show: '/module/[id]/show'),
  ),
  settings: '/settings',
);
