// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: '/login', uri: Uri.parse('/login'), routeBuilder: b0Builder),
  RouteEntity(
    key: '/splash',
    uri: Uri.parse('/splash'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(key: '/home', uri: Uri.parse('/home'), routeBuilder: b2Builder),
  RouteEntity(
    key: '/settings',
    uri: Uri.parse('/settings'),
    routeBuilder: b3Builder,
  ),
];

const routePaths = (
  path: '/',
  login: '/login',
  splash: '/splash',
  home: '/home',
  settings: '/settings',
);
